apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
  namespace: backend
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    semver: "*"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: memcached
  namespace: backend
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/memcached
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: backend
spec:
  interval: 30m
  releaseName: redis
  chartRef:
    kind: OCIRepository
    name: redis
  values:
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memcached
  namespace: backend
spec:
  interval: 30m
  releaseName: memcached
  chartRef:
    kind: OCIRepository
    name: memcached
