apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: velero
  namespace: velero
spec:
  interval: 24h
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 30m
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
  values:
    installCRDs: true
    configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: velero-backups
          config:
            region: us-east-1
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: us-east-1
    schedules:
      daily:
        schedule: "0 1 * * *"
        template:
          ttl: "720h0m0s"
